# SignalRouter 자동매매 시스템 설정

# 데이터베이스 설정
database:
  path: "data/trading.db"
  backup_enabled: true
  backup_interval_hours: 6

# 웹훅 서버 설정
webhook:
  host: "0.0.0.0"
  port: 8000
  secret_key: "your-secret-key-here"
  allowed_ips: []  # 빈 리스트면 모든 IP 허용

# KIS API 설정
kis_api:
  prod_url: "https://openapi.koreainvestment.com:9443"
  vps_url: "https://openapivts.koreainvestment.com:29443"
  token_storage_path: "secrets/tokens/"
  auto_reauth: true
  timeout_seconds: 30
  retry_count: 3
  retry_delay_seconds: 5

# 계좌 설정
accounts:
  futures_real_01:
    name: "선물 실전 계좌 01"
    type: "FUTURES"
    secret_file: "secrets/futures_real_01.json"
    is_virtual: false
    is_active: true
  
  stock_virtual_01:
    name: "주식 모의 계좌 01"
    type: "STOCK"
    secret_file: "secrets/stock_virtual_01.json"
    is_virtual: true
    is_active: true

  futures_virtual_01:
    name: "선물 모의 계좌 01"
    type: "FUTURES"
    secret_file: "secrets/futures_virtual_01.json"
    is_virtual: true
    is_active: true

# 전략별 설정
strategies:
  FUTURES_MOMENTUM:
    account_id: "futures_real_01"
    webhook_token: "webhook_token_2"
    max_position_ratio: 1
    max_daily_loss: 3000000
    is_active: false
  
  TEST_STRATEGY:
    account_id: "stock_virtual_01"
    webhook_token: "webhook_token_3"
    max_position_ratio: 1
    max_daily_loss: 1000000
    is_active: true
  
  FUTURES_TEST:
    account_id: "futures_virtual_01"
    webhook_token: "webhook_token_4"
    max_position_ratio: 1
    leverage: 10
    max_daily_loss: 1000000
    is_active: true

# 리스크 관리 설정
risk_management:
  # 전역 설정
  global_max_daily_loss: 10000000  # 전체 계좌 일일 최대 손실
  position_timeout_seconds: 60    # 포지션 전환 대기 시간
  order_retry_count: 3           # 주문 재시도 횟수
  order_retry_delay_seconds: 5   # 재시도 간격
  
  # 거래 시간 제한
  trading_hours:
    start_time: "05:00"
    end_time: "09:00"
    timezone: "Asia/Seoul"

# 로깅 설정
logging:
  level: "INFO"
  file_path: "logs/trading.log"
  max_file_size_mb: 10
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# 대시보드 설정
dashboard:
  host: "0.0.0.0"
  port: 8501
  title: "SignalRouter Dashboard"
  refresh_interval_seconds: 5

# 알림 설정 (향후 확장용)
notifications:
  enabled: false
  slack_webhook: ""
  telegram_bot_token: ""
  telegram_chat_id: ""

# 선물 상품 매핑 설정
futures_mapping:
  symbol_mapping:
    USDKRW: "175W"      # 원/달러 선물
    GOLD: "188W"        # 금 선물
    KOSPI200: "101W"    # 코스피200 선물
  
  multipliers:
    "175W": 10000       # 원/달러 선물 승수
    "188W": 100      # 금 선물 승수
    "101W": 250000      # 코스피200 선물 승수
  
  market_codes:
    "175W": "CF"        # 통화선물
    "188W": "CF"        # 상품선물
    "101W": "F"         # 지수선물
  
  expiry_rules:
    "175W":
      type: "second_thursday"    # 셋째 주 목요일
      months_ahead: 1          # 1개월 후까지
    "188W":
      type: "second_thursday"
      months_ahead: 1
    "101W":
      type: "second_thursday"   # 둘째 주 목요일
      months_ahead: 3