# SignalRouter 자동매매 시스템 설정

webhook:
  host: "0.0.0.0"
  port: 8000

accounts:
  futures_real:
    account_id: "futures_real"
    name: "Won-Dollar Futures Real"
    type: "FUTURES"
    is_virtual: false
    is_active: true
    secret_file: "secrets/futures_real_01.json"
  
  futures_virtual:
    account_id: "futures_virtual"
    name: "Won-Dollar Futures Virtual"
    type: "FUTURES"
    is_virtual: true
    is_active: true
    secret_file: "secrets/futures_virtual_01.json"
    
  stock_virtual_01:
    account_id: "stock_virtual"
    name: "Stock Virtual"
    type: "STOCK"
    is_virtual: true
    is_active: true
    secret_file: "secrets/stock_virtual_01.json"

strategies:
  trend_follow_real:
    account_id: "futures_real"
    webhook_token: "webhook_token_2"
    is_active: true
  
  trend_follow_virtual:
    account_id: "futures_virtual"
    webhook_token: "webhook_token_4"
    is_active: true

kis_api:
  token_storage_path: "secrets/tokens/"

notifier:
  enabled: false